### ISSUE TITLE
Notify when new client joins the network

### ISSUE THREAD

**Issue by icornish72** [amosyuen/ha-tplink-deco#74]
Is it possible to add a Device Count for each Deco unit, and a Total Device Count?
Then we can use this as a trigger for an automation

**Comment by amosyuen** [comment]
Sounds reasonable for device count per deco unit as an attribute.

I'm not so sure about adding a total device count because it doesn't belong on an existing entity, so you would need a new entity for that. If users care about the total count they can always create their own using templated sensor that sumbs up the deco attributes.

**Comment by amosyuen** [comment]
Based on your use case, I think what might actually be more useful is to have an event fired when a new client is added? Then you can have an automation listen for the event and send a notification with the name of the new client.

**Comment by Silvrav** [comment]
second this, this would be great

**Comment by amosyuen** [comment]
Seems like this can be done through listening to the `entity_registry_updated` event. Here's an automation I am using:

```yaml
- alias: Notify New Wifi Device
  mode: parallel
  max: 100
  trigger:
    - platform: event
      event_type: entity_registry_updated
      event_data:
        action: create
  variables:
    id: "{{ trigger.event.data.entity_id }}"
  condition:
    - condition: template
      value_template: "{{ id.split('.')[0] == 'device_tracker' }}"
    - condition: template
      value_template: "{{ id in integration_entities('tplink_deco') }}"
  action:
    - wait_template: "{{ states(id) not in ['unknown', 'unavailable'] }}"
      timeout:
        minutes: 1
    - service: notify.mobile_app_amos_phone
      data:
        title: "{{ state_attr(id, 'friendly_name') or id }} connected to WiFi"
        message: >-
          {{ id }} connected to
          {{ state_attr(id, 'interface') }}
          {{
            state_attr(id, 'connection_type')
              | regex_replace('band', '')
              | regex_replace('_', '.')
              | regex_replace('$', 'G')
          }}
          through
          {{ state_attr(id, 'deco_device') }}
        data:
          group: wifi-new-device
          clickAction: "entityId:{{ id }}"
```
